import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Product } from '../models/product.model';
import { User } from '../models/user.model';

dotenv.config();

const products = [
  {
    name: 'Classic White Oxford Shirt',
    description: 'A timeless Oxford shirt crafted from premium cotton fabric. Features a button-down collar, chest pocket, and relaxed fit for everyday elegance. Perfect for both casual and semi-formal occasions.',
    price: 1299,
    originalPrice: 1999,
    category: 'Shirts',
    brand: 'Urban Thread',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600'],
    stock: 45,
    rating: 4.5,
    reviewCount: 128,
    features: ['100% Premium Cotton', 'Button-Down Collar', 'Machine Washable', 'Regular Fit'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Light Blue', 'Pink'],
  },
  {
    name: 'Slim Fit Dark Indigo Jeans',
    description: 'Premium denim jeans with a modern slim fit silhouette. Made from stretch denim for maximum comfort and mobility. Features a classic five-pocket design with contrast stitching.',
    price: 1799,
    originalPrice: 2499,
    category: 'Jeans',
    brand: 'Denim Co',
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=600'],
    stock: 60,
    rating: 4.3,
    reviewCount: 256,
    features: ['2% Elastane Stretch Denim', 'Slim Fit', 'Five-Pocket Design', 'Fade Resistant'],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Dark Indigo', 'Black', 'Medium Wash'],
  },
  {
    name: 'Premium Graphic Tee - Abstract',
    description: 'Bold abstract graphic t-shirt made from ultra-soft combed cotton. Features a modern oversized fit with ribbed crew neckline and premium print that won\'t fade after washing.',
    price: 699,
    originalPrice: 999,
    category: 'T-Shirts',
    brand: 'Street Style',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600'],
    stock: 100,
    rating: 4.6,
    reviewCount: 89,
    features: ['100% Combed Cotton', 'Oversized Fit', 'Premium Print', 'Pre-Shrunk'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Navy'],
  },
  {
    name: 'Leather Bomber Jacket',
    description: 'Premium faux leather bomber jacket with quilted lining for warmth. Features a classic ribbed collar, cuffs and hem. Two outer pockets and one inner pocket for functionality.',
    price: 3499,
    originalPrice: 4999,
    category: 'Jackets',
    brand: 'Metro Edge',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600'],
    stock: 25,
    rating: 4.7,
    reviewCount: 67,
    features: ['Premium Faux Leather', 'Quilted Lining', 'Ribbed Cuffs & Hem', 'Multi-Pocket'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown', 'Tan'],
  },
  {
    name: 'Floral Summer Dress',
    description: 'Lightweight floral dress perfect for summer days. Made from breathable viscose fabric with a flattering A-line silhouette, adjustable waist tie, and side pockets.',
    price: 1599,
    originalPrice: 2199,
    category: 'Dresses',
    brand: 'Bloom',
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600'],
    stock: 35,
    rating: 4.4,
    reviewCount: 145,
    features: ['100% Viscose', 'A-Line Silhouette', 'Side Pockets', 'Adjustable Waist'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Blue Floral', 'Pink Floral', 'Yellow Floral'],
  },
  {
    name: 'Classic Canvas Sneakers',
    description: 'Iconic canvas sneakers with a vulcanized rubber sole for superior grip and durability. Features cushioned insole, breathable canvas upper, and classic low-top design.',
    price: 2299,
    originalPrice: 2999,
    category: 'Shoes',
    brand: 'StepUp',
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600'],
    stock: 80,
    rating: 4.5,
    reviewCount: 312,
    features: ['Canvas Upper', 'Rubber Sole', 'Cushioned Insole', 'Breathable'],
    sizes: ['UK6', 'UK7', 'UK8', 'UK9', 'UK10', 'UK11'],
    colors: ['White', 'Black', 'Navy', 'Red'],
  },
  {
    name: 'Premium Leather Belt',
    description: 'Handcrafted genuine leather belt with brushed metal buckle. Features a single-prong classic design with five adjustment holes for perfect fit.',
    price: 899,
    originalPrice: 1299,
    category: 'Accessories',
    brand: 'CraftLeather',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'],
    stock: 50,
    rating: 4.2,
    reviewCount: 78,
    features: ['Genuine Leather', 'Brushed Metal Buckle', 'Adjustable', 'Handcrafted'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Brown', 'Tan'],
  },
  {
    name: 'Performance Running Shorts',
    description: 'Lightweight running shorts with moisture-wicking DryFit technology. Features a built-in brief liner, side mesh ventilation panels, and zippered back pocket.',
    price: 999,
    originalPrice: 1499,
    category: 'Activewear',
    brand: 'FitPro',
    images: ['https://images.unsplash.com/photo-1562886877-aaaa5c18396c?w=600'],
    stock: 70,
    rating: 4.4,
    reviewCount: 193,
    features: ['DryFit Material', 'Built-in Liner', 'Mesh Ventilation', 'Zippered Pocket'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Grey'],
  },
  {
    name: 'Striped Polo T-Shirt',
    description: 'Classic striped polo with a pique knit construction. Features a ribbed collar, two-button placket, and embroidered logo. Perfect for a smart-casual look.',
    price: 899,
    originalPrice: 1399,
    category: 'T-Shirts',
    brand: 'Urban Thread',
    images: ['https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600'],
    stock: 55,
    rating: 4.3,
    reviewCount: 112,
    features: ['Pique Knit Cotton', 'Ribbed Collar', 'Two-Button Placket', 'Regular Fit'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White/Navy', 'Black/White', 'Red/White'],
  },
  {
    name: 'Chino Trousers - Khaki',
    description: 'Versatile chino trousers in premium cotton twill. Features a tapered fit, flat front, and side and back pockets. Ideal for office or weekend wear.',
    price: 1499,
    originalPrice: 2199,
    category: 'Jeans',
    brand: 'Metro Edge',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600'],
    stock: 40,
    rating: 4.1,
    reviewCount: 86,
    features: ['100% Cotton Twill', 'Tapered Fit', 'Flat Front', 'Wrinkle Resistant'],
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Khaki', 'Navy', 'Olive'],
  },
  {
    name: 'Waterproof Windbreaker',
    description: 'Lightweight windbreaker with waterproof coating and sealed seams. Features a packable hood, adjustable cuffs, and reflective accents for low-light visibility.',
    price: 2499,
    originalPrice: 3499,
    category: 'Jackets',
    brand: 'FitPro',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600'],
    stock: 30,
    rating: 4.6,
    reviewCount: 54,
    features: ['Waterproof Coating', 'Packable Hood', 'Reflective Accents', 'Lightweight'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Olive'],
  },
  {
    name: 'Oversized Hoodie - Vintage Wash',
    description: 'Ultra-comfortable oversized hoodie with vintage acid wash finish. Made from heavyweight fleece with a kangaroo pocket, adjustable drawstring hood, and ribbed cuffs.',
    price: 1599,
    originalPrice: 2299,
    category: 'T-Shirts',
    brand: 'Street Style',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600'],
    stock: 65,
    rating: 4.8,
    reviewCount: 201,
    features: ['Heavyweight Fleece', 'Vintage Wash', 'Oversized Fit', 'Kangaroo Pocket'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Sand', 'Forest Green'],
  },
  {
    name: 'Formal Blazer - Navy',
    description: 'Tailored single-breasted blazer in premium wool blend. Features notch lapels, two-button closure, functional sleeve buttons, and interior pockets. Perfect for formal occasions.',
    price: 4999,
    originalPrice: 6999,
    category: 'Jackets',
    brand: 'CraftLeather',
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600'],
    stock: 20,
    rating: 4.7,
    reviewCount: 43,
    features: ['Wool Blend', 'Slim Fit', 'Notch Lapels', 'Fully Lined'],
    sizes: ['36', '38', '40', '42', '44'],
    colors: ['Navy', 'Charcoal', 'Black'],
  },
  {
    name: 'Athletic Performance Tee',
    description: 'High-performance athletic t-shirt with four-way stretch and moisture management. Raglan sleeves for unrestricted movement, flatlock seams to prevent chafing.',
    price: 799,
    originalPrice: 1199,
    category: 'Activewear',
    brand: 'FitPro',
    images: ['https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600'],
    stock: 90,
    rating: 4.5,
    reviewCount: 167,
    features: ['4-Way Stretch', 'Moisture Wicking', 'Raglan Sleeves', 'Flatlock Seams'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Grey', 'Blue'],
  },
  {
    name: 'Aviator Sunglasses',
    description: 'Classic aviator sunglasses with UV400 protection and polarized lenses. Lightweight metal frame with adjustable nose pads and spring hinges for comfort.',
    price: 1299,
    originalPrice: 1999,
    category: 'Accessories',
    brand: 'Metro Edge',
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600'],
    stock: 40,
    rating: 4.3,
    reviewCount: 92,
    features: ['UV400 Protection', 'Polarized Lenses', 'Spring Hinges', 'Lightweight Metal'],
    sizes: ['One Size'],
    colors: ['Gold/Green', 'Silver/Blue', 'Black/Grey'],
  },
  {
    name: 'Linen Summer Shirt',
    description: 'Relaxed-fit linen shirt perfect for warm weather. Features a Mandarin collar, roll-up sleeves with button tabs, and a curved hemline. Breathable and effortlessly stylish.',
    price: 1199,
    originalPrice: 1799,
    category: 'Shirts',
    brand: 'Bloom',
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600'],
    stock: 35,
    rating: 4.4,
    reviewCount: 76,
    features: ['100% Linen', 'Mandarin Collar', 'Roll-Up Sleeves', 'Relaxed Fit'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Sky Blue', 'Sage Green'],
  },
  {
    name: 'Running Shoes - Cloud Series',
    description: 'Lightweight running shoes with cloud-cushion technology for maximum impact absorption. Engineered mesh upper for breathability, rubber outsole for durability.',
    price: 3999,
    originalPrice: 5499,
    category: 'Shoes',
    brand: 'StepUp',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600'],
    stock: 45,
    rating: 4.6,
    reviewCount: 234,
    features: ['Cloud Cushion', 'Engineered Mesh', 'Rubber Outsole', 'Lightweight Design'],
    sizes: ['UK6', 'UK7', 'UK8', 'UK9', 'UK10', 'UK11'],
    colors: ['Black/Red', 'White/Blue', 'Grey/Orange'],
  },
  {
    name: 'Printed Wrap Dress',
    description: 'Elegant wrap dress in luxe jersey fabric with a vibrant geometric print. Features a v-neckline, self-tie waist, and midi length. Flattering for all body types.',
    price: 1999,
    originalPrice: 2799,
    category: 'Dresses',
    brand: 'Bloom',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600'],
    stock: 30,
    rating: 4.5,
    reviewCount: 108,
    features: ['Jersey Fabric', 'Wrap Style', 'Self-Tie Waist', 'Midi Length'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Blue Print', 'Red Print', 'Green Print'],
  },
  {
    name: 'Canvas Backpack',
    description: 'Durable canvas backpack with leather trim details. Features padded laptop compartment (fits up to 15"), multiple organizer pockets, and adjustable shoulder straps.',
    price: 1799,
    originalPrice: 2499,
    category: 'Accessories',
    brand: 'Urban Thread',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600'],
    stock: 30,
    rating: 4.4,
    reviewCount: 156,
    features: ['Heavy-Duty Canvas', 'Padded Laptop Sleeve', 'Leather Trim', 'Multiple Pockets'],
    sizes: ['One Size'],
    colors: ['Olive', 'Navy', 'Grey'],
  },
  {
    name: 'Yoga Leggings - High Rise',
    description: 'High-rise yoga leggings with buttery-soft fabric and four-way stretch. Features a hidden waistband pocket, flatlock seams, and moisture-wicking technology.',
    price: 1299,
    originalPrice: 1899,
    category: 'Activewear',
    brand: 'FitPro',
    images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600'],
    stock: 55,
    rating: 4.7,
    reviewCount: 289,
    features: ['4-Way Stretch', 'High Rise', 'Hidden Pocket', 'Moisture Wicking'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'Wine', 'Forest'],
  },
  {
    name: 'Denim Jacket - Classic Blue',
    description: 'Timeless denim jacket in classic blue wash. Made from 100% cotton denim with authentic vintage detailing, button front closure, and adjustable waist tabs.',
    price: 2799,
    originalPrice: 3799,
    category: 'Jackets',
    brand: 'Denim Co',
    images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=600'],
    stock: 35,
    rating: 4.5,
    reviewCount: 178,
    features: ['100% Cotton Denim', 'Classic Wash', 'Button Front', 'Adjustable Tabs'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Classic Blue', 'Light Wash', 'Dark Wash'],
  },
  {
    name: 'Formal Leather Oxford Shoes',
    description: 'Premium leather Oxford shoes with Goodyear welt construction. Features a cap-toe design, leather sole with rubber heel, and cushioned insole for all-day comfort.',
    price: 4499,
    originalPrice: 5999,
    category: 'Shoes',
    brand: 'CraftLeather',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=600'],
    stock: 20,
    rating: 4.8,
    reviewCount: 67,
    features: ['Genuine Leather', 'Goodyear Welt', 'Cap-Toe Design', 'Cushioned Insole'],
    sizes: ['UK6', 'UK7', 'UK8', 'UK9', 'UK10', 'UK11'],
    colors: ['Black', 'Tan', 'Burgundy'],
  },
  {
    name: 'Silk Pocket Square Set',
    description: 'Set of 3 premium silk pocket squares in coordinating patterns. Hand-rolled edges with impeccable finish. Comes in an elegant gift box for gifting.',
    price: 599,
    originalPrice: 999,
    category: 'Accessories',
    brand: 'Metro Edge',
    images: ['https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600'],
    stock: 40,
    rating: 4.2,
    reviewCount: 45,
    features: ['100% Silk', 'Hand-Rolled Edges', 'Set of 3', 'Gift Box'],
    sizes: ['One Size'],
    colors: ['Classic Set', 'Bold Set', 'Pastel Set'],
  },
  {
    name: 'Checked Flannel Shirt',
    description: 'Warm brushed flannel shirt in classic check pattern. Features a button-down collar, dual chest pockets, and a comfortable relaxed fit. Perfect for layering.',
    price: 1099,
    originalPrice: 1599,
    category: 'Shirts',
    brand: 'Urban Thread',
    images: ['https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=600'],
    stock: 45,
    rating: 4.3,
    reviewCount: 134,
    features: ['Brushed Flannel', 'Button-Down Collar', 'Dual Chest Pockets', 'Relaxed Fit'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Red/Black', 'Blue/White', 'Green/Navy'],
  },
];

const seedProducts = async () => {
  try {
    const mongoUri = process.env.MONGO_URI || process.env.MONGODB_URI || 'mongodb://localhost:27017/ecommerce';
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB');

    // Drop existing collections to clear old indexes
    try {
      await mongoose.connection.db!.collection('products').drop();
      console.log('Dropped products collection');
    } catch (e) {
      console.log('No existing products collection to drop');
    }
    try {
      await mongoose.connection.db!.collection('users').drop();
      console.log('Dropped users collection');
    } catch (e) {
      console.log('No existing users collection to drop');
    }

    // Insert seed data
    const inserted = await Product.insertMany(products);
    console.log(`✅ Successfully seeded ${inserted.length} products`);

    // Create demo user
    await User.deleteMany({});
    const demoUser = new User({
      name: 'Demo User',
      email: 'demo@luxestore.com',
      password: 'demo123',
      phone: '9876543210',
    });
    await demoUser.save();
    console.log('✅ Demo user created (demo@luxestore.com / demo123)');

    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
};

seedProducts();
